server.port: 9090
spring.datasource.url: jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username: "sys as sysdba"
spring.datasource.password: "0000"
spring.datasource.driver.class: oracle.jdbc.driver.OracleDriver